name: pre-commit-auto-update

on:
  schedule:
    - cron: '0 0 1,14,28 * *'

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Run pre-commit
        run: pre-commit run --all

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update/pre-commit-autoupdate
          title: Auto-update pre-commit hooks
          commit-message: Auto-update pre-commit hooks
          body: Update versions of tools in pre-commit config to latest versions.
          labels: dependencies
